### ISSUE TITLE
Please add two papers

### ISSUE THREAD

**Issue by LonglongaaaGo** [AlonzoLeeeooo/awesome-image-inpainting-studies#1]
Could you please add two papers:

EXE-GAN: https://longlongaaago.github.io/EXE-GAN/
GRIG: https://github.com/LonglongaaaGo/GRIG_few_shot_inpainting

Thanks!

**Comment by AlonzoLeeeooo** [comment]
Updated in [this commit](https://github.com/AlonzoLeeeooo/awesome-image-inpainting-studies/commit/0f15f496c963f91714231074cefb4d07c0959251). Please check.

**Comment by LonglongaaaGo** [comment]
@AlonzoLeeeooo 
Thanks! I appreciate!

Best
