### ISSUE TITLE
能解释stable diffusion如何做inpainting吗?

### ISSUE THREAD

**Issue by wr0124** [AlonzoLeeeooo/awesome-image-inpainting-studies#2]
inpainting在pixel空间操作很好理解,但是到了latent空间就不好理解了。 latent空间是把图像用特征表示,失去了pixel空间位置信息,那是如何做到找到mask区域的呢? 进入latext空间后的矩阵维度位置和pixel空间维度位置没有对应关系吧?

**Comment by AlonzoLeeeooo** [comment]
你好，diffusion model天然就是可以做inpainting的，具体的做法其实在去噪过程中不断用`mask`将模型输出的中间样本跟ground truth做拼接。

举一个具体的例子：给定输入图像`image`，破损区域`mask`，如果我们观察$x_t$到$x_{t-1}$这一步的话，具体实现可以写成：
```python
pred_noise = unet(x_t, t, text_condition)
noisy_image_t = noise_scheduler(image, t)
pred_noise = noisy_image_t * (1 - mask) + mask * pred_noise
# Other operations
# And then run the next step
```
这样一来经过`timesteps`步数的迭代，模型最后预测的部分仅有`mask`内部的部分，也就实现了inpainting。

不过事实上更加有效的做法还是跟传统inpainting网络一样，将`mask`和`masked_image`作为额外输入，concat输入U-net，相关的一些工作可以关注Paint by Example、AnyDoor、Stable Diffusion Inpaint。

VAE这个事，其实VAE latents跟图像像素是有一定空间一致性的。你可以用一个VQ-VAE，尝试将编码后的VAE latents强行当作RGB图像保存到本地，你会发现可视化出来的结果更像“下采样后的RGB图像”。事实上你可以看下CompVis最早[`latent-diffusion`](https://github.com/CompVis/latent-diffusion/tree/main/scripts)那一版代码inpainting模型的实现（[`latent-diffusion/scripts/inpaint.py`](https://github.com/CompVis/latent-diffusion/blob/main/scripts/inpaint.py)中的第`77-78`行），里面的mask是直接下采样8倍（用的VAE是`kl-f8`）跟VAE latents对齐的。

以上，希望能帮到你。

**Comment by wr0124** [comment]
非常感谢这样详尽的回复! 在pixel空间中的inpainting操作很了解。 我想当mask在pixel空间是确定的时候,到了latent空间会维度小很多,那样在恢复到pixel空间的时候,要经过缩放过程,会有很多信息损失, 直觉上觉得mask再次到pixel空间后会边界变化很大,和原来的mask不同了。  就是你说的"VAE latents跟图像像素是有一定空间一致性的",非常感谢提供背景资料!

**Comment by AlonzoLeeeooo** [comment]
> 非常感谢这样详尽的回复! 在pixel空间中的inpainting操作很了解。 我想当mask在pixel空间是确定的时候,到了latent空间会维度小很多,那样在恢复到pixel空间的时候,要经过缩放过程,会有很多信息损失, 直觉上觉得mask再次到pixel空间后会边界变化很大,和原来的mask不同了。 就是你说的"VAE latents跟图像像素是有一定空间一致性的",非常感谢提供背景资料!

不客气~
